name: 'Go Test with Coverage'
description: 'Run Go tests and generate coverage report'

outputs:
  coverage-file:
    description: 'Path to coverage output file'
    value: 'coverage.out'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Running Tests
      shell: bash
      run: |
        go mod vendor
        go mod tidy
        CGO_ENABLED=0 go test -cover -coverprofile=coverage.out -mod=vendor -v -count=1 ./...

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: coverage.out