name: 'Go Lint'
description: 'Run Go linting with golangci-lint'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Run linter
      uses: golangci/golangci-lint-action@v8
      with:
        install-mode: "binary"
        version: "latest"