name: Changelog

on:
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
    secrets:
      changelog-app-id:
        required: true
      changelog-app-token:
        required: true

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Generate release changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff-release
        with:
          config: cliff.toml
          args: -v --latest --strip header
        env:
          OUTPUT: RELEASE-CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create a release
        uses: svenstaro/upload-release-action@v2
        with:
          file: CHANGELOG.md
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          body: |
            # 🐙 ${{ inputs.docker-image-name }} ${{ github.ref_name }}

            ${{ steps.git-cliff-release.outputs.content }}

            ---

            > Docker images for this release can be found at public.ecr.aws/p3k6k6h3/${{ inputs.docker-image-name }}:${{ github.ref_name }}
      

      - name: Get changelog app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.changelog-app-id }}
          private-key: ${{ secrets.changelog-app-token }}
          owner: ${{ github.repository_owner }}
          repositories: changelogs

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Checkout changelog repo
        uses: actions/checkout@v4
        with:
          repository: DecisiveAI/changelogs
          path: ./mdai-changelogs
          ref: rlaw/testing-auto-changelogs
# TODO: FIX THE BRANCH AT THE END OF THE LINE ABOVE! REJECT THIS PR!

      - name: Commit changelog
        run: |
          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          cd ./mdai-changelogs
          cp ../CHANGELOG.md ./${{ inputs.docker-image-name }}.md
          set +e
          git add ${{ inputs.docker-image-name }}.md
          git commit -m "Update ${{ inputs.docker-image-name }} changelog for ${{ github.ref_name }}"
          git push https://${{ steps.app-token.outputs.token }}@github.com/DecisiveAI/changelogs.git rlaw/testing-auto-changelogs
# TODO: FIX THE BRANCH AT THE END OF THE LINE ABOVE! REJECT THIS PR!

