name: Go Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint on Ubuntu
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Run Go lint
        uses: decisiveai/ci/go-lint@45efd1d9a3b3b65fd7e2e1e4fee22f31d4473db8
        with:
          timeout: 5m