name: Go Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint on Ubuntu
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Run Go lint
        uses: decisiveai/ci/go-lint@e7af2d3f21d9f52bf7b88a07b5a08b7fd4db91bd
        with:
          timeout: 5m