name: PR Coverage

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to test coverage config'
        type: string
        required: false
        default: '../../coverage-report/.testcoverage.yml'
    secrets:
      github-token:
        description: 'GitHub token for API access'
        required: true

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  report-coverage:
    name: Report code coverage
    runs-on: ubuntu-latest

    steps:
      - name: Generate coverage report
        uses: decisiveai/ci/coverage-report@e7af2d3f21d9f52bf7b88a07b5a08b7fd4db91bd
        with:
          config-path: ${{ inputs.config-path }}
          github-token: ${{ secrets.github-token }}
          timeout: 15m