name: Notify Slack

on:
  workflow_call:
    secrets:
      SLACK_BLARP_URL:
        required: true
    inputs:
      ref:
        required: true
        type: string
      run_id:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo:
        required: true
        type: string
      workflow:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \":x: **${{ inputs.repo_name }}** workflow '${{inputs.workflow}}' failed on ref: ${{ inputs.ref }}\nRun: https://github.com/${{ inputs.repo }}/actions/runs/${{ inputs.run_id }}\"}" \
            "${{ secrets.SLACK_BLARP_URL }}"
