name: Notify Slack

on:
  workflow_call:
    secrets:
      SLACK_BLARP_URL:
        required: true
    # inputs:
    #   ref_name:
    #     required: true
    #     type: string
    #   run_id:
    #     required: true
    #     type: string
    #   repo_name:
    #     required: true
    #     type: string
    #   repo:
    #     required: true
    #     type: string
    #   workflow:
    #     required: true
    #     type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"${{ github.repository }}\n:x: Workflow '${{github.workflow}}' failed on ref: ${{ github.ref_name }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "${{ secrets.SLACK_BLARP_URL }}"
        
        # run: |
        #   curl -X POST -H 'Content-type: application/json' \
        #     --data "{\"text\": \"${{ inputs.repo_name }}\n:x: Workflow '${{inputs.workflow}}' failed on ref: ${{ inputs.ref_name }}\nRun: https://github.com/${{ inputs.repo }}/actions/runs/${{ inputs.run_id }}\"}" \
        #     "${{ secrets.SLACK_BLARP_URL }}"
